version: '3.8'

services:
  api:
    build: ./api          # Caminho para o diretório onde está o Dockerfile da sua aplicação
    ports:
      - "8800:8800"
    depends_on:
      - mysql

  mysql:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: mydatabase
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql

volumes:
  mysql-data:
